### ISSUE TITLE
database changes not reaching simpl state

### ISSUE THREAD

**Issue by janeeisenstein** [simplworld/simpl-calc-ui#3]
After upgrading simpl-games-api to Django 2.2, database changes are not reaching the  redux simpl state.

Steps to reproduce:
1. Run simpl-games-api following README directions.
1. Run simpl-calc-model's `./manage.py create_default_env`
1. Run simpl-calc-model's `./manage.py run_modelservice`
1. Run simpl-calc-ui following README directions.
1. Log in as s1@calc.edu / s1 using Chrome.
1. Enter a number and click *Add to Total*

The Current total should update to reflect the number you entered, but it doesn't. The simpl-calc-model's console log includes a sequence similar to this:
```
2019-08-21T11:48:27+0000 [Guest       92740] 2019-08-21T11:48:27 submit_decision: Key: details
[Guest       92740] 2019-08-21T11:48:27 submit_decision: Key: user
[Guest       92740] 2019-08-21T11:48:28 submit_decision: saved decision
[Guest       92740] 2019-08-21T11:48:29 submit_decision: stepped scenario
```
indicating the decision was successfully submitted and a result produced. Examining the database confirms a decision and a result were stored.

The Redux simpl state does not contain the decision or the result. This indicates the database changes did not reach the browser.

**Comment by janeeisenstein** [comment]
FYI the simpl-calc-model service needs to register webhooks when it starts up.

Here's an example from pop-model's startup:
```
[Guest       41890] 2019-08-21T11:06:04 Starting scopes 0%...
[Guest       41890] 2019-08-21T11:06:04 Starting scopes 5%...
[Guest       41890] 2019-08-21T11:06:04 Starting scopes 50%...
[Guest       41890] 2019-08-21T11:06:04 Starting scopes 55%...
[Guest       41890] 2019-08-21T11:06:04 webhook registered for prefix `pop.*`
[Guest       41890] 2019-08-21T11:06:04 webhook registered for prefix `user.*`
[Guest       41890] 2019-08-21T11:06:04 game `pop` installed
[Guest       41890] 2019-08-21T11:06:04 Game `pop` installed in 1.067s.
```

**Comment by janeeisenstein** [comment]
@jefftriplett Verified that I can successfully run Django 2.2 simpl-calc-model and simpl-calc-ui against simpl-games-api v0.7.9. This lays the blame squarely on the Django 2.2 upgraded simpl-games-api.

**Comment by frankwiles** [comment]
Yes, you need simpl-games-api running on 8100

--
Frank Wiles
President/Founder of REVSYS
www.revsys.com
@fwiles

**Comment by janeeisenstein** [comment]
I corrected the issue description to include running simpl-games-api.

**Comment by jefftriplett** [comment]
I have the parts all connected now. I can see thorn dispatching requests. modelservice was suppressing some errors with crossbar which I have never worked for before. So maybe we can upgrade some deps there? Pinging @frankwiles to see how to move forward and I'll check back.

**Comment by janeeisenstein** [comment]
We have a ticket to upgrade simpl-modelservice's crossbar simplworld/simpl-modelservice#10 that @frank thought might be difficult.

**Comment by janeeisenstein** [comment]
When simpl-calc-model runs for the first time against the upgraded simpl-games-api, its webhooks are re-registered in the webhooks_subscriber table.

**Comment by janeeisenstein** [comment]
When simpl-calc-model runs for the first time against the upgraded simpl-games-api, its webhooks are re-registered in the webhooks_subscriber table.

**Comment by janeeisenstein** [comment]
Corrected by running with simpl-games-api 0v0.8.0.
